Team-Offroad/Offroad-server

README.md
* README.md 초안 작성 완료했습니다!
* https://github.com/Team-Offroad/Offroad-server/tree/task/README
* 빠진내용이나 추가하면 좋을 내용, 잘못된 내용 있으면 말씀 바로 해주시면 감사하겠습니다 ㅡㅡ
=> [feat] README.md 업데이트

build.gradle, src/main/java/site/offload/offloadserver/HealthCheckController.java, src/main/java/site/offload/offloadserver/HealthCheckControllerSwagger.java, src/main/java/site/offload/offloadserver/common/api/config/SwaggerConfig.java
https://github.com/Team-Offroad/Offroad-server/blob/6f609c2b4855553250ba9667a4e572d2ff4c4690/src/main/java/site/offload/offloadserver/common/api/config/SwaggerConfig.java#L9-L25
* common/api/config로 경로를 설정했습니다. 
* JWT를 고려하지 않은 상태로 Config를 세팅하였습니다.
https://github.com/Team-Offroad/Offroad-server/blob/6f609c2b4855553250ba9667a4e572d2ff4c4690/src/main/java/site/offload/offloadserver/HealthCheckControllerSwagger.java#L9-L17
* HealthCheck를 인터페이스로 만들어 테스트 해보았습니다.
* 고칠 점이나 추가해야할 점 있으시면 말씀해주시면 감사하겠습니다 ㅡㅡ
=> [feat] : Swgger 세팅

.github/workflows/dev-CD.yaml, .github/workflows/dev-CI.yaml, src/main/java/site/offload/offloadserver/api/HealthCheckController.java, src/main/java/site/offload/offloadserver/api/HealthCheckControllerSwagger.java, src/main/java/site/offload/offloadserver/api/config/SwaggerConfig.java, src/main/resources/application-dev.yaml, src/main/resources/application-local.yaml, src/main/resources/application.yaml
* HealthCheck와 관련된 파일을 api패키지 아래에 이동시켰습니다.
* yaml 파일들에 discord-url을 추가하고 github secret에도 업데이트 하였습니다.
* application.yaml을 추가하고 local.yaml을 활성화 하도록 했습니다.
* CI/CD 를 pr이 아닌 push하는 경우에 실행하도록 변경했습니다
* 로컬에서는 디스코드가 사용될 일이 없기에 application-local.yaml에는 url을 추가하지 않으려 했지만 DiscordService에서 이 환경변수를 불러와야하기 때문에 설정했습니다.
* 잘못된 점이나 수정할 부분 있으면 편하게 말씀해 주시면 감사하겠습니다. ㅡㅡ
=> [fix] 기초 설정 충돌 해결

build.gradle, src/main/java/site/offload/offloadserver/api/exception/GlobalExceptionHandler.java, src/main/resources/application-dev.yaml
- Sentry 설정을 진행했습니다. 우선 InternalServerError에 대해서만 진행했고, 이후에 4xx까지 추가하는 방향으로 진행하겠습니다 ~
=> setting: Sentry 설정

src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java, src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
https://github.com/Team-Offroad/Offroad-server/blob/80cb3915887ab428ab429f7823ecee244f557746/src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java#L15
https://github.com/Team-Offroad/Offroad-server/blob/80cb3915887ab428ab429f7823ecee244f557746/src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java#L3-L6
* 매개변수를 추가해서 오류를 해결했습니다.
* 잘못된 부분이 있으면 말씀해주시면 감사하겠습니다 ㅡㅡ
=> [fix] : ErrorAPIResponse 오류 해결

src/main/java/site/offload/offloadserver/api/member/dto/request/MemberProfileUpdateRequest.java, src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java, src/main/java/site/offload/offloadserver/api/place/controller/PlaceController.java, src/main/java/site/offload/offloadserver/api/place/controller/PlaceControllerSwagger.java, src/main/java/site/offload/offloadserver/api/place/dto/constans/PlaceConstants.java, src/main/java/site/offload/offloadserver/api/place/dto/request/RegisteredPlacesRequest.java, src/main/java/site/offload/offloadserver/api/place/dto/response/RegisteredPlaceResponse.java, src/main/java/site/offload/offloadserver/api/place/dto/response/RegisteredPlacesResponse.java, src/main/java/site/offload/offloadserver/api/place/service/PlaceService.java, src/main/java/site/offload/offloadserver/api/place/usecase/PlaceUsecase.java, src/main/java/site/offload/offloadserver/common/auth/JwtAuthenticationFilter.java, src/main/java/site/offload/offloadserver/common/auth/PrincipalHandler.java, src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java, src/main/java/site/offload/offloadserver/db/place/entity/Place.java, src/main/java/site/offload/offloadserver/db/place/entity/VisitedPlace.java, src/main/java/site/offload/offloadserver/db/place/repository/PlaceRepository.java, src/main/java/site/offload/offloadserver/db/place/repository/VisitedPlaceRepositoiry.java
https://github.com/Team-Offroad/Offroad-server/blob/dfc6f658ef9311d2358484074455c94bb6659d40/src/main/java/site/offload/offloadserver/api/place/service/PlaceService.java#L23-L25
https://github.com/Team-Offroad/Offroad-server/blob/dfc6f658ef9311d2358484074455c94bb6659d40/src/main/java/site/offload/offloadserver/db/place/repository/PlaceRepository.java#L10-L14
* 쿼리문을 이용해서 일정 경위도에 있는 장소를 조회하도록 했습니다.
https://github.com/Team-Offroad/Offroad-server/blob/dfc6f658ef9311d2358484074455c94bb6659d40/src/main/java/site/offload/offloadserver/db/place/repository/VisitedPlaceRepositoiry.java#L10-L12
https://github.com/Team-Offroad/Offroad-server/blob/dfc6f658ef9311d2358484074455c94bb6659d40/src/main/java/site/offload/offloadserver/api/place/service/PlaceService.java#L27-L32
* countBy를 이용해 memberId와 …
=>  [feat] 오프로드 등록 장소 조회 API

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/dto/MemberAdventureInformationResponse.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
- 모험 정보 API 에서 응답 값으로 캐릭터 이름을 추가했습니다. 
- 추가로 MemberUseCase에서 에러를 수정했습니다.
- https://github.com/Team-Offroad/Offroad-server/blob/60cfb490d6fe0cd1ccd90ddf35945e9580a3e02e/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L32-L34
=> [fix] 반환값에 캐릭터 이름 추가

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java, src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java, src/main/java/site/offload/offloadserver/db/member/embeddable/Birthday.java, src/main/java/site/offload/offloadserver/db/member/entity/Member.java
https://github.com/Team-Offroad/Offroad-server/blob/0990fc12f0e7ba980b8ca48b649664564a982261/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L69-L73
https://github.com/Team-Offroad/Offroad-server/blob/0990fc12f0e7ba980b8ca48b649664564a982261/src/main/java/site/offload/offloadserver/db/member/entity/Member.java#L54-L77
* member 엔티티에 생년월일 필드를 추가하고 updateProfile 메소드를 통해 업데이트하도록 했습니다.
=> [feat] 프로필 업데이트 API 

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java, src/main/java/site/offload/offloadserver/api/member/dto/response/NicknameCheckResponse.java, src/main/java/site/offload/offloadserver/api/member/service/MemberService.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java, src/main/java/site/offload/offloadserver/db/member/repository/MemberRepository.java
https://github.com/Team-Offroad/Offroad-server/blob/92c3f5d8a77f6efeb380804c45b5561fbc4f9b79/src/main/java/site/offload/offloadserver/api/member/service/MemberService.java#L22-L24
https://github.com/Team-Offroad/Offroad-server/blob/92c3f5d8a77f6efeb380804c45b5561fbc4f9b79/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L96-L102
* existsBy를 이용하여 중복되는 닉네임이 있는지 확인했습니다.
=> [feat] : 닉네임 중복확인 API 

src/main/java/site/offload/offloadserver/api/character/service/GainedCharacterService.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java, src/main/java/site/offload/offloadserver/db/character/entity/GainedCharacter.java, src/main/java/site/offload/offloadserver/db/member/entity/Member.java
https://github.com/Team-Offroad/Offroad-server/blob/d53189b5a5abe6007fde3d10bfc13e165aec7875/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L106-L112
https://github.com/Team-Offroad/Offroad-server/blob/d53189b5a5abe6007fde3d10bfc13e165aec7875/src/main/java/site/offload/offloadserver/db/member/entity/Member.java#L84-L86
* memberId와 characterId를 받아 해당 character를 member에 이름으로 대입했습니다.
* GainedCharacterService를 추가하여 얻은 캐릭터와 함께 저장했습니다.
=> [feat] 캐릭터 선택 API

src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginController.java, src/main/java/site/offload/offloadserver/api/member/dto/request/SocialPlatform.java, src/main/java/site/offload/offloadserver/api/member/service/SocialLoginService.java, src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java, src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenParser.java, src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenValidator.java, src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKey.java, src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeyGenerator.java, src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeysResponse.java, src/main/java/site/offload/offloadserver/external/oauth/apple/AppleSocialLoginService.java, src/main/resources/application-local.yaml
https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleSocialLoginService.java#L31-L46
* claim에서 name, email, sub를 가져와 member를 build하였습니다.
https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/AppleIdentityTokenParser.java#L20-L45
* 인증코드를 이용하여 Map<String, String>으로 파싱합니다.
* 인증코드와 publicKey로 이용하여 정보가 담긴 claim을 생성합니다.
https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009c0fae0a/src/main/java/site/offload/offloadserver/external/oauth/apple/ApplePublicKeysResponse.java#L8-L16
https://github.com/Team-Offroad/Offroad-server/blob/1c2cf303a96fa8bb28d2914090fee9009 …
=> [feat] : Apple Social Login 구현

src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java
https://github.com/Team-Offroad/Offroad-server/blob/509b05d0a199150d2f1c4f205ca393286a807d96/src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java#L78-L90
* 발생할 수 있는 여러 예외처리를 명시했습니다.
* token이 없는 경우는 IllegalArgumentException이 발생하는데 이에 대한 예외처리가 존재하지 않았습니다. 그렇기에 다양한 오류를 추가하였습니다.
=> [fix] security 수정

src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java
- SecurityConfig에서 필터체인에 /api/health 경로를 추가했습니다.
- 배포 스크립트 파일에서 서버 상태 확인하는 코드로 /api/health를 이용하고 있는데 ,현재 develop 브랜치에 필터체인에 white list로 등록되지 않아 CD 과정 중 헬스체크가 안되는 것 같아 이에 대해 확인해보려고 합니다.
=> [fix] 필터체인 수정

src/main/java/site/offload/offloadserver/db/character/entity/Character.java
- Mysql 예약어 이슈로 캐릭터 테이블 명 수정합니다,
=> [fix] 캐릭터 테이블 이름 수정

src/main/java/site/offload/offloadserver/db/place/entity/Place.java, src/main/java/site/offload/offloadserver/db/place/entity/PlaceArea.java, src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java, src/main/java/site/offload/offloadserver/db/quest/entity/ProceedingQuest.java, src/main/java/site/offload/offloadserver/db/quest/entity/Quest.java, src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java, src/main/java/site/offload/offloadserver/db/quest/repository/QuestRepository.java, src/main/java/site/offload/offloadserver/db/quest/repository/QuestRewardRepository.java, src/main/resources/application-local.yaml
- 퀘스트 enum -> 퀘스트 엔티티로 수정
- 퀘스트 테이블 필드로 아래와 같이 장소카테고리, 장소 구역 추가
https://github.com/Team-Offroad/Offroad-server/blob/919fa6b7dc916d4b4a191d13d4c8c91f9abc1bed/src/main/java/site/offload/offloadserver/db/quest/entity/Quest.java#L10-L29
------------------------------------------
- 장소 테이블에 탐험 인증에 사용할 UUID, 장소 구역 추가
- 보상 목록을 뜻하는 RewardList를 Embed 값으로 정의
- 진행중인 퀘스트를 뜻하는 ProceedingQuest를 Member <-> Quest 중간테이블로 정의
=> [fix] 퀘스트 테이블 관련 수정

.github/workflows/dev-CD.yaml, docker-compose.yml, src/main/java/site/offload/offloadserver/api/HealthCheckController.java
- 프로젝트 루트 경로에 docker-compose.yml 파일 생성
- CD 스크립트 작동시 docker-compose.yml 파일 ec2 /home/ubuntu 경로로 전송
- ec2 서버에 있는 deploy.sh 파일 수정
=> [fix] 도커 컴포즈 세팅 수정

src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java, src/main/java/site/offload/offloadserver/api/place/usecase/PlaceUsecase.java, src/main/java/site/offload/offloadserver/api/quest/controller/QuestController.java, src/main/java/site/offload/offloadserver/api/quest/dto/response/HomeQuestResponse.java, src/main/java/site/offload/offloadserver/api/quest/dto/response/QuestInformationResponse.java, src/main/java/site/offload/offloadserver/api/quest/service/QuestService.java, src/main/java/site/offload/offloadserver/api/quest/usecase/QuestUseCase.java, src/main/java/site/offload/offloadserver/db/quest/entity/ProceedingQuest.java, src/main/java/site/offload/offloadserver/db/quest/entity/Quest.java, src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java, src/main/java/site/offload/offloadserver/db/quest/repository/ProceedingQuestRepository.java, src/main/resources/application-local.yaml
https://github.com/Team-Offroad/Offroad-server/blob/845704cbaa5138347c7390306659e229f42037db/src/main/java/site/offload/offloadserver/api/quest/service/QuestService.java#L14-L19
* memberId를 이용해 진행중인 퀘스트를 찾고 최근 진행한 퀘스트를 찾기 위해 수정일을 기준으로 정렬하다.
https://github.com/Team-Offroad/Offroad-server/blob/845704cbaa5138347c7390306659e229f42037db/src/main/java/site/offload/offloadserver/api/quest/usecase/QuestUseCase.java#L24-L27
* 진행 중인 퀘스트를 따로 모았습니다.
https://github.com/Team-Offroad/Offroad-server/blob/845704cbaa5138347c7390306659e229f42037db/src/main/java/site/offload/offloadserver/api/quest/usecase/QuestUseCase.java#L29-L34
https://github.com/Team-Offroad/Offroad-server/blob/845704cbaa5138347c7390306659e229f42037db/src/main/java/site/offload/offloadserver/api/quest/usecase/QuestUseCase.java#L36-L48
* …
=> [feat] : 퀘스트 정보 조회API 

src/main/java/site/offload/offloadserver/api/place/dto/constans/PlaceConstants.java, src/main/java/site/offload/offloadserver/db/character/entity/Character.java, src/main/java/site/offload/offloadserver/db/charactermotion/entity/CharacterMotion.java
- TEXT 필드에 unique=true 조건 삭제, PlaceConstants에 필드 값 0.085로 섲ㅇ
=> [chore] TEXT 컬럼 수정, PlaceConstants 수정

src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java, src/main/java/site/offload/offloadserver/db/member/entity/Member.java
- Emblem enum 클래스에 데이터 추가했습니다.
=> [setting] 칭호 데이터 넣기

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
- MemberUseCase에서 getQuests 메소드
- 카테고리나 구역이 NONE이 아닌 경우에만 가져오도록 수정
=> [chore] 탐험 인증 시 퀘스트 불러오기 수정

src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterResponse.java, src/main/java/site/offload/offloadserver/api/character/service/CharacterService.java, src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java, src/main/java/site/offload/offloadserver/db/character/repository/CharacterRepository.java
- CharacterResponse에 @Builder를 클래스에서 생성
- 메소드에 사용시 stack over flow 에러
=> [fix] CharacerResponse dto 스택오버플로우 오류

src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java, src/main/java/site/offload/offloadserver/db/place/entity/Place.java, src/main/java/site/offload/offloadserver/db/place/entity/VisitedPlace.java, src/main/java/site/offload/offloadserver/db/quest/entity/Quest.java, src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java
- BaseTimeEntity 상속, Member필드 UUID를 String 타입으로 변경
=> [chore] BaseTimeEntity, UUID -> String 수정

build.gradle, src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/external/aws/S3UseCase.java, src/main/java/site/offload/offloadserver/external/config/AwsConfig.java, src/main/resources/application-local.yaml
- s3 설정파일, usecase 추가했습니다
- gradle 의존성 추가했습니다
- yml파일 aws 설정 추가했습니다
- presigend url로 생성 후, DTO에 해당 url을 포함시켜서 응답합니다.
- 이미지 등 url DB에 저장 시 , 경로 전체가 아닌 버킷 내 객체의 key를 저장해야 됩니다.
=> [feat] presigned url

src/main/java/site/offload/offloadserver/api/character/dto/response/CharacterResponse.java, src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java
- CharacterResponse DTO에 Character 이름 (name) 추가했습니다.
- 화면 설계서 상 포함되어야 하는 캐릭터의 이름을 추가했습니다.
=> [fix] 캐릭터 조회시 이름 반환

src/main/java/site/offload/offloadserver/api/place/dto/response/RegisteredPlaceResponse.java, src/main/java/site/offload/offloadserver/api/place/usecase/PlaceUsecase.java, src/main/java/site/offload/offloadserver/db/place/entity/Place.java
* 오프로드 등록 장소를 불러올 때 해당 장소의 카테고리 이미지를 불러올 수 있도록 했습니다.
=> [fix] : 카테고리 이미지 추가

src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/common/auth/JwtAuthenticationFilter.java
=> [fix] : refreshToken 발급 로직 수정

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
=>  [fix] : 캐릭터 중복 확인 응답 포맷 수정

README.md
=> [fix] : readme 수정

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java, src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java, src/main/java/site/offload/offloadserver/api/member/dto/response/ChooseCharacterResponse.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/db/character/entity/Character.java
- 캐릭터 선택 이후 스포트라이트를 받는 캐릭터 이미지를 반환하도록 응답 body에 추가했습니다.
- Character 필드에 기존 characterBaseImageUrl 외에 별도로 characterSpotLightImageUrl를 추가했습니다.
=> [fix] 캐릭터 선택 이후 스포트라이트 이미지 반환

src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginController.java, src/main/java/site/offload/offloadserver/api/member/controller/SocialLoginControllerSwagger.java, src/main/java/site/offload/offloadserver/api/member/dto/response/SocialLoginResponse.java, src/main/java/site/offload/offloadserver/api/member/usecase/SocialLoginUseCase.java
* 기존 유저인지를 판단할 수 있는 필드값을 추가했습니다.
=> [fix] : 기존 유저 판별 필드 추가

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/api/quest/service/CompleteQuestService.java, src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java, src/main/java/site/offload/offloadserver/db/quest/repository/CompleteQuestRepository.java, src/main/resources/application-local.yaml
- 탐험인증 API에서 인증과정 중 일어나는 에러사항 수정
- https://github.com/Team-Offroad/Offroad-server/blob/13c26b9703ddca1b9cb31e1a10688c9adb412d27/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L235-L242
- Quest의 아이디를 현재 Reward 테이블 목록에 있는 보상 대상 Quest의 id만 처리할 수 있도록 분기처리했습니다. 이유는 현재 보상 목록을 전부 DB에 저장한 상태가 아니라 필요한 것들만 해놧기 때문입니다. 이후에 보상 데이터가 확립 될 경우 if문은 삭제할 예정입니다!
-------------------------------------------------
- https://github.com/Team-Offroad/Offroad-server/blob/13c26b9703ddca1b9cb31e1a10688c9adb412d27/src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java#L230-L232
- 완료된 퀘스트인지 확인하는 로직을 추가했습니다.
=> [fix] 모험인증수정

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
- src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java 에서 캐릭터모션을 찾는 부분의 조건문을 수정했습니다.
=> [fix] 조건문 수정

src/main/java/site/offload/offloadserver/api/member/dto/request/MemberProfileUpdateRequest.java, src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java, src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java
- setec 용 칭호 enum 데이터 생성 및 칭호 보상 추가했습니다!
=> [feat] 보상 추가 및 setec 세팅

src/main/java/site/offload/offloadserver/db/member/entity/Member.java
=> [chore] member 엔티티 필드수정

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java, src/main/java/site/offload/offloadserver/external/aws/S3UseCase.java
* imageUrl를 presignUrl로 바꾸도록 했습니다~!
=> [hotfix] : presignUrl 변환

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
* 캐릭터 생성 시 기본 emblem을 저장할 수 있도록 했습니다!
=> [hotfix] : 기본 emblem 저장

src/main/java/site/offload/offloadserver/api/character/usecase/CharacterUseCase.java, src/main/java/site/offload/offloadserver/db/character/entity/Character.java
* 캐릭터 조회 시 기본 이미지가 아닌 선택 이미지를 반환하도록 했습니다.
=> [fix] : 캐릭터 조회 시 캐릭터 선택 이미지 반환

build.gradle, src/main/java/site/offload/offloadserver/db/place/entity/Place.java, src/test/java/site/offload/offloadserver/api/place/service/PlaceServiceTest.java, src/test/java/site/offload/offloadserver/integration/IntegrationTest.java
Jacoco 세팅 및 Jacoco report 확인을 위해서  PlaceService의 단위 테스트를 작성했습니다.
test report 화면입니다.
Service layer 단위테스트는 Mockito를 활용하여 진행하는 것으로 하면 좋을 것 같습니다 ~
=> [test] Jacoco 세팅

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
=> [fix] 퀘스트 추가

src/main/java/site/offload/offloadserver/api/exception/GlobalExceptionHandler.java
- GloablExceptionHandle에서 sentry 전송 코드 추가했습니다.
- ec2에서 로그 파일이 일정 용량과 일정 개수를 넘어 가지 않게 설정했습니다. https://jun-codinghistory.tistory.com/796
=> [feat] sentry 전송 코드 추가

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
* 탐험 인증 반경을 조금 넓혔습니다.
* 데모데이 이후 변경이 필요합니다!!
=> [fix] : 탐험 인증 반경 범위 증가

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
=> [chore] 오차 수정

.github/workflows/dev-CD.yaml, .github/workflows/dev-CI.yaml, Dockerfile-dev, offroad-api/src/main/java/site/offload/api/HealthCheckController.java
- 멀티모듈 프로젝트 구조 변경에 따라 cicd 관련 workflows 파일과 Dockerfile-dev를 수정했습니다
- dev-CD 파일과 dev-CI 파일의 디렉토리를 ./offroad-api 밑으로 빌드되고, yml파일등이 위치하게 변경했습니다
- Dockerfile-dev의 WORKDIR를 ./offroad-api 밑으로 변경했습니다
- pull request 시 cicd로 정상 작동하는 것을 확인했고, 현재 push로 다시 바꿔놓은 상태입니다
=> [fix] cicd 빌드 경로 수정

offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
- 애플 로그인 시 Member 객체 builder에서 SocialPlatForm의  lowercase() 제거
=> [fix] 애플 로그인 에러 수정

offroad-api/src/main/java/site/offload/api/auth/SecurityConfig.java, offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java, offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java, offroad-api/src/main/java/site/offload/api/member/dto/request/SignOutRequest.java, offroad-api/src/main/java/site/offload/api/member/usecase/SignOutUseCase.java, offroad-cache/src/main/java/site/offload/cache/config/RedisRepository.java, offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
로그아웃 API 요청을 하면 인증 정보를 없애기 위하여, Redis에서 RefreshToken을 삭제합니다.
-
-
-
=> [feat] 로그아웃 API 구현

offroad-enum/src/main/java/site/offload/enums/emblem/Emblem.java
- Emblem enum값 추가
- 팀 노션 기반 칭호 추가했습니다
=> chore: 칭호 목록 업데이트

offroad-enum/src/main/java/site/offload/enums/emblem/Emblem.java
=> fix: 칭호 중복 수정

offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java, offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java, offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java, offroad-api/src/test/java/site/offload/api/character/service/GainedCharacterServiceTest.java, offroad-api/src/test/java/site/offload/api/character/usecase/GainedCharacterUseCaseTest.java, offroad-api/src/test/java/site/offload/api/charactermotion/service/CharacterMotionServiceTest.java, offroad-api/src/test/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCaseTest.java, offroad-api/src/test/java/site/offload/api/fixture/CharacterEntityFixtureCreator.java, offroad-api/src/test/java/site/offload/api/member/usecase/AuthAdventureUseCaseTest.java, offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java
* 클라이언트 분들과 API에 대해서 얘기해 본 뒤 수정이 필요한 부분들을 반영했습니다
* issue = #168
=> [fix] : 캐릭터 목록 조회 시 응답 값 수정 

offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java, offroad-api/src/main/java/site/offload/api/member/dto/response/UserInfoResponse.java, offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java, offroad-api/src/main/java/site/offload/api/place/service/VisitedPlaceService.java, offroad-api/src/main/java/site/offload/api/quest/service/CompleteQuestService.java, offroad-api/src/main/java/site/offload/api/util/TimeUtil.java, offroad-db/src/main/java/site/offload/db/place/repository/VisitedPlaceRepository.java, offroad-db/src/main/java/site/offload/db/quest/repository/CompleteQuestRepository.java, offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java
close #177 
- 사용자 정보 조회 API를 구현했습니다
=> 사용자 정보 조회 API 개발

offroad-api/src/main/java/site/offload/api/auth/jwt/JwtTokenProvider.java
- 클라이언트에서 Access Token시간 변경 요청하여 일시적으로 Token 만료 시간을 변경합니다.
=> chore: AccessToken 만료시간 변경

offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
- 안드측에서 공원 탐험 인증 테스트를 위해 인증 범위를 일시적으로 넓혀달라는 요청이 있어서 일시적으로 수정합니다
=> chore: 공원 인증 범위 수정

offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
=> chore: 공원 탐험 인증 범위 수정

offroad-api/src/main/java/site/offload/api/auth/jwt/JwtTokenProvider.java
- 클라측 요청에 따라 토큰 유효시간을 2분으로 일시적으로 수정합니다
=> chore: 토큰 유효시간 수정

offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java, offroad-api/src/main/resources/application-local.yaml, offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java
=> fix: 장소 조회 API 쿼리 수정

offroad-api/src/main/java/site/offload/api/member/dto/response/MemberAdventureInformationResponse.java, offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
- 홈화면에서 반환 값에 모션 캡쳐 이미지 추가했습니다.
=> chore: 홈화면 모션캡쳐이미지 반환 추가

offroad-api/src/main/java/site/offload/api/character/controller/CharacterControllerSwagger.java, offroad-api/src/main/java/site/offload/api/coupon/controller/CouponControllerSwagger.java, offroad-api/src/main/java/site/offload/api/emblem/controller/EmblemControllerSwagger.java, offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java, offroad-api/src/main/java/site/offload/api/member/controller/TokenControllerSwagger.java, offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
- 제가 맡은 api 중 기존 swagger에서 4xx 에러 세분화, 2xx 에러 수정, 각 예외 별 반환 값 설정, 파라미터 추가 등을 진행했습니다
=> refactor: swagger 문서 정보 추가

offroad-api/src/main/java/site/offload/api/coupon/dto/CouponApplyRequest.java, offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponApplyUseCase.java, offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponApplyUseCaseTest.java
- 쿠폰 사용 api에서 클라이언트로부터 요청값으로 오는 placeId를 제거했습니다.
- 관련 테스트코드 수정했습니다.
=> fix: 쿠폰 인증 시 장소 id 요청값 제거

offroad-api/src/main/java/site/offload/api/character/controller/CharacterControllerSwagger.java, offroad-api/src/main/java/site/offload/api/charactermotion/controller/CharacterMotionControllerSwagger.java, offroad-api/src/main/java/site/offload/api/emblem/controller/EmblemControllerSwagger.java, offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java, offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java, offroad-api/src/main/java/site/offload/api/place/controller/PlaceController.java, offroad-api/src/main/java/site/offload/api/place/controller/PlaceControllerSwagger.java, offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
* 소셜로그인 API를 제외한 API swagger작업 완료하였습니다.
* 소셜 로그인 DTO가 external 모듈에 있어서 swagger의존성을 추가해야했는데, 그렇게 하지 않고 DTO를 옮기려 했으나 external에서 이 request를 사용하고 있어 오류가 발생했습니다. 이는 다음에 수정하도록 하겠습니다.
=> [refact] : swagger 명세서 업데이트

offroad-api/src/main/java/site/offload/api/member/dto/response/UserInfoResponse.java, offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
- 마이페이지 api 응답값에 현재 선택한 캐릭터의 기본 이미지를 반환하도록 응답값에 포함시켰습니다.
=> chore: 마이페이지 캐릭터 이미지 추가

offroad-api/src/main/java/site/offload/api/coupon/dto/AvailableCouponResponse.java, offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponListUseCase.java, offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponApplyUseCaseTest.java, offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponListUseCaseTest.java, offroad-api/src/test/java/site/offload/api/place/service/PlaceEntityServiceTest.java
- 쿠폰 리스트 응답 시 불필요한 placeId를 제거했습니다
- 쿠폰 관련 테스트에서 오류가 나 수정했습니다
=> chore: 쿠폰 리스트 응답값 수정
