Team-Offroad/Offroad-server

src/main/java/site/offload/offloadserver/common/api/message/ErrorMessage.java
src/main/java/site/offload/offloadserver/common/api/message/SuccessMessage.java
src/main/java/site/offload/offloadserver/common/api/response/APIErrorResponse.java
src/main/java/site/offload/offloadserver/common/api/response/APISuccessResponse.java

https://github.com/Team-Offroad/Offroad-server/blob/75cc6468e120590e34f7f09333428f818f356228/src/main/java/site/offload/offloadserver/common/api/response/APISuccessResponse.java#L5-L12
* 제네릭 타입 T를 이용했습니다.
https://github.com/Team-Offroad/Offroad-server/blob/75cc6468e120590e34f7f09333428f818f356228/src/main/java/site/offload/offloadserver/common/api/response/APIErrorResponse.java#L7-L13
https://github.com/Team-Offroad/Offroad-server/blob/75cc6468e120590e34f7f09333428f818f356228/src/main/java/site/offload/offloadserver/common/api/message/ErrorMessage.java#L9-L12
* RequiredArgsConstructor를 사용했습니다.
* common 패키지 아래에 api패키지를 만들었습니다. 그리고 그 아래 response, message 패키지를 따로 만들어 생성했습니다. 
* 세미나에서는 ok(), created(), badRequest() 등 특정한 상황을 가정해서 사용했어서 일반적으로 포맷을 어떻게 구상할지 고민이었습니다. 그러다 status를 이용하여 이 부분에 상태코드를 …

[feat] API 응답 포맷 세팅

---

src/main/java/site/offload/offloadserver/api/exception/RestClientException.java
src/main/java/site/offload/offloadserver/api/exception/RestClientUseCase.java
src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
src/main/java/site/offload/offloadserver/external/discord/DiscordService.java
src/main/java/site/offload/offloadserver/external/discord/DiscordWebhookRequest.java
src/main/java/site/offload/offloadserver/external/discord/Embed.java

- application.local-yaml 파일 수정
```yaml
spring:
application:
name: offloadserver
config:
activate:
on-profile: local
discord:
webhook-url: {디스코드 채널 웹훅 url}
```
- external/discord 디렉토리 아래 웹훅 알림에 필요한 DiscordService, DiscordWebhookRequest, Embed 클래스 작성 
- API 통신 방법으로 처음에는 OpenFeign을 채택했습니다. 하지만 더 찾아보니 스프링 공식문서에서 OpenFeign에 대해 더 이상 기능 구현을 하지 않는 다는 것과 다른 방식으로 migrating하는 것을 권장하는 내용을 찾았습니다.([관련 문서](https://spring.io/projects/spring-cloud-openfeign)). 그래서 RestClient와 WebClient 사이에서 고민했고, RestClient가 저희 서비스 규모에 적당하고 구현이 간결하며 Spring Framework 자체 기술이라는 점에서 RestClient를 선택하고 구현했습니다.
- 디스코드 알림으로 운영 서버의 에러만 전송할지, 로컬 서버에서 각자 테스트 할 때 발생하는 에러도 전송할지 고민했습니다. 두 경우 모두 알림으로 발송하는 것이 서로 의논하며 디버깅하는 것에 도움을 줄 것 같아 두 경우 모두 알림 발송하는 쪽으로 구현했습니다.
- 운영 서버와 로컬 서버의 구분: application-local.yaml과 application-dev.yaml에서 구분되는 …

[feat] SpringBoot -> Discord 웹훅 연결

---

src/main/java/site/offload/offloadserver/common/config/JpaAuditingConfig.java
src/main/java/site/offload/offloadserver/db/entity/Announcement.java
src/main/java/site/offload/offloadserver/db/entity/BaseTime.java
src/main/java/site/offload/offloadserver/db/entity/BaseTimeEntity.java
src/main/java/site/offload/offloadserver/db/entity/Character.java
src/main/java/site/offload/offloadserver/db/entity/CharacterMotion.java
src/main/java/site/offload/offloadserver/db/entity/Coupon.java
src/main/java/site/offload/offloadserver/db/entity/Emblem.java
src/main/java/site/offload/offloadserver/db/entity/GainedCharacter.java
src/main/java/site/offload/offloadserver/db/entity/GainedCoupon.java
src/main/java/site/offload/offloadserver/db/entity/GainedEmblem.java
src/main/java/site/offload/offloadserver/db/entity/Member.java
src/main/java/site/offload/offloadserver/db/entity/MemberGender.java
src/main/java/site/offload/offloadserver/db/entity/Place.java
src/main/java/site/offload/offloadserver/db/entity/PlaceCategory.java
src/main/java/site/offload/offloadserver/db/entity/Quest.java
src/main/java/site/offload/offloadserver/db/entity/VisitedPlace.java
src/main/java/site/offload/offloadserver/db/repository/AnnouncementRepository.java
src/main/java/site/offload/offloadserver/db/repository/CharacterMotionRepository.java
src/main/java/site/offload/offloadserver/db/repository/CharacterRepository.java
src/main/java/site/offload/offloadserver/db/repository/CouponRepository.java
src/main/java/site/offload/offloadserver/db/repository/GainedCharacterRepository.java
src/main/java/site/offload/offloadserver/db/repository/GainedCouponRepository.java
src/main/java/site/offload/offloadserver/db/repository/GainedEmblemRepository.java
src/main/java/site/offload/offloadserver/db/repository/MemberRepository.java
src/main/java/site/offload/offloadserver/db/repository/PlaceRepository.java
src/main/java/site/offload/offloadserver/db/repository/VisitedPlaceRepositoiry.java

- ERD 토대로 Entity 및 Repository 세팅
- 생성자 Builder 패턴으로 엔티티 생성 로직 통일했습니다
- Column 어노테이션 등을 통해 서비스 요구 사항대로 DB 제약 조건 반영하려고 해봤습니다
- 각 엔티티의 생성시간, 업데이트 시간을 저장하기 위해 JPA Auditing을 사용했습니다. (BaseTime 클래스 상속)
- PlaceCategory에 NONE 값을 넣어놨는데, 서비스 요구 사항 중 장소 별 로티 발동 조건이 있으므로 이에 null보단 카테고리 없음을 나타내는 NONE 타입이 있으면 좋을 것 같아 추가했습니다
- 개선해야 할 점, 수정해야 할 점, 추가해야할 데이터 필드 코멘트 부탁드립니다!

[feat] Entity Setting

---

src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java
src/main/java/site/offload/offloadserver/api/member/controller/TokenControllerSwagger.java
src/main/java/site/offload/offloadserver/api/member/dto/response/TokenReissueResponse.java
src/main/java/site/offload/offloadserver/api/member/service/MemberUseCase.java
src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java

- TokenController, MemberUseCase에 토큰 관련 로직
- TokenController를 member 패키지 아래에 정의했습니다.
- https://github.com/Team-Offroad/Offroad-server/blob/cdde27e02c5b15f5fc3c0edc088b56ce503ea98e/src/main/java/site/offload/offloadserver/api/member/controller/TokenController.java#L16-L30
--------------------------------------------
- 재발급 로직은 아래와 같습니다.
- https://github.com/Team-Offroad/Offroad-server/blob/cdde27e02c5b15f5fc3c0edc088b56ce503ea98e/src/main/java/site/offload/offloadserver/api/member/service/MemberUseCase.java#L14-L32
- Jwt 필터에서 토큰에 대한 검증은 한 번 하기 때문에 서비스 로직에서는 Refresh Token이 Redis에 존재하는지 체크하고, 없다면 예외처리를 해줬습니다.

[feat] 토큰 재발급 API

---

src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemControllSwawgger.java
src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemController.java
src/main/java/site/offload/offloadserver/api/emblem/dto/request/UpdateCurrentEmblemRequest.java
src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java
src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
src/main/java/site/offload/offloadserver/api/member/dto/request/MemberAdventureInformationRequest.java
src/main/java/site/offload/offloadserver/api/member/dto/response/MemberAdventureInformationResponse.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/api/message/CustomErrorCode.java
src/main/java/site/offload/offloadserver/api/message/ErrorMessage.java
src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
src/main/java/site/offload/offloadserver/db/emblem/entity/Emblem.java
src/main/java/site/offload/offloadserver/db/emblem/repository/GainedEmblemRepository.java
src/main/java/site/offload/offloadserver/db/member/entity/Member.java

- EmblemController, UseCase 작성, Emblem 클래스 수정, 관련 에러메세지 및 성공 메시지 추가
- Emblem 클래스에서 칭호가 있는지 없는지 판단하는 메소드 추가했습니다.
```java
@RequiredArgsConstructor
@Getter
public enum Emblem  {
DEFAULT_EMBLEM("0001", "오프로드 스타터");
private final String emblemCodeName;
private final String emblemName;
public static boolean isExistsEmblem(Emblem emblem) {
for (Emblem thisEmblem : Emblem.values()) {
if (emblem.equals(thisEmblem)) {
return true;
}
}
return false;
}
}
````
--------------------------------------------------------------------
- EmblemUseCase에서 칭호를 변경하는 메소드를 추가했습니다. 칭호가 존재하지 않으면 에러를 반환합니다.
```java
@Transactional
public void updateCurrentEmblem(UpdateCurrentEmblemRequest request) {
if (isExistsEmblem(request.emblemName())) {
Member findMember = memberService.findById(request.memberId()); …
```

[feat] 칭호 변경 API

---

src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemControllSwawgger.java
src/main/java/site/offload/offloadserver/api/emblem/controller/EmblemController.java
src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemListResponse.java
src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemResponse.java
src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java
src/main/java/site/offload/offloadserver/api/message/SuccessMessage.java
src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java
src/main/java/site/offload/offloadserver/db/emblem/repository/GainedEmblemRepository.java

- EmblemController 수정
----------------------------------
- 칭호 조회에 필요한 DTO 클래스 정의
- https://github.com/Team-Offroad/Offroad-server/blob/595ba5b5041b15f66daeee4284c263544751542b/src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemListResponse.java#L5-L9
- https://github.com/Team-Offroad/Offroad-server/blob/595ba5b5041b15f66daeee4284c263544751542b/src/main/java/site/offload/offloadserver/api/emblem/dto/response/GainedEmblemResponse.java#L4-L9
------------------------------------------
- EmblemUseCase 로직 추가
- https://github.com/Team-Offroad/Offroad-server/blob/595ba5b5041b15f66daeee4284c263544751542b/src/main/java/site/offload/offloadserver/api/emblem/usecase/EmblemUseCase.java#L44-L50
- 멤버가 얻은 칭호를 반환하도록 했습니다
- Repository에서는 List 형태로 반환하도록 해서 값이 없다면 null이 아닌 빈 리스트를 …

[feat] 칭호 조회 API

---

build.gradle
src/main/java/site/offload/offloadserver/OffloadserverApplication.java
src/main/java/site/offload/offloadserver/common/auth/SecurityConfig.java
src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java
src/main/java/site/offload/offloadserver/external/oauth/google/GoogleSocialLoginService.java
src/main/java/site/offload/offloadserver/external/oauth/google/request/GoogleApiClient.java
src/main/java/site/offload/offloadserver/external/oauth/google/request/GoogleAuthApiClient.java
src/main/java/site/offload/offloadserver/external/oauth/google/response/GoogleAuthResponse.java
src/main/java/site/offload/offloadserver/external/oauth/google/response/GoogleInfoResponse.java

https://github.com/Team-Offroad/Offroad-server/blob/e35a966f325a5b43f0bfe80c564d91e3e0c6819e/src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java#L68-L73
* redis에 저장할 때 key를 refreshtoken으로 설정했습니다.
https://github.com/Team-Offroad/Offroad-server/blob/e35a966f325a5b43f0bfe80c564d91e3e0c6819e/src/main/java/site/offload/offloadserver/external/oauth/google/GoogleSocialLoginService.java#L35-L47
https://github.com/Team-Offroad/Offroad-server/blob/e35a966f325a5b43f0bfe80c564d91e3e0c6819e/src/main/java/site/offload/offloadserver/external/oauth/google/response/GoogleInfoResponse.java#L6-L15
* RestClient에서 OpenFeign으로 변경하여 구글 소셜 로그인을 구현했습니다.
* /v2/me 엔드포인트는 구글 개인 id가 "sub"가 아닌 "id"로 전송해서 DTO의 이름을 id로 수정했습니다.

[fix] : 구글 소셜 로그인

---

src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/db/charactermotion/repository/GainedCharacterMotionRepository.java

- GaiendCharacterMotionService에서 GainedCharacterRepository -> GainedCharacterMotionRepository로 수정
- MemberUseCase에서 if문 조건 수정
```java
if (!PlaceCategory.isExistsCategory(placeCategory)) {
throw new NotFoundException(ErrorMessage.PLACE_CATEGORY_NOTFOUND_EXCEPTION);
}
```

[fix] 얻은 캐릭터 모션 리포 생성 및 모험 정보 APi 수정

---

src/main/java/site/offload/offloadserver/api/emblem/service/GainedEmblemService.java
src/main/java/site/offload/offloadserver/api/member/service/SocialLoginService.java
src/main/java/site/offload/offloadserver/db/emblem/entity/GainedEmblem.java

- SocialLoginService
- 유저가 회원가입 시 기본 칭호를 얻게 했습니다. -> GainedEmblem 테이블 컬럼 추가
- 로그인 요청이 여러 번 오기 때문에 DB에 exists 쿼리로 확인 후 저장합니다.

[fix] 멤버 회원가입시 기본 칭호 GainedEmblem db에 추가

---

src/main/java/site/offload/offloadserver/api/character/service/CharacterService.java
src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
src/main/java/site/offload/offloadserver/api/member/dto/request/MemberAdventureInformationRequest.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/db/character/repository/CharacterRepository.java

- 모험 정보 조회 API에서, 파라미터로 받던 characterId를 삭제했습니다.
- 이유는 이슈 내용에 적어놨습니다! #97  
- 현재 유저가 선택한 캐릭터 이름으로 캐릭터에 대한 정보를 가져왔습니다

[fix] 모험 정보 조회 API에서 characterId 요청 이슈

---

src/main/java/site/offload/offloadserver/api/charactermotion/service/GainedCharacterMotionService.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/api/quest/service/CompleteQuestService.java
src/main/java/site/offload/offloadserver/api/quest/service/ProceedingQuestService.java
src/main/java/site/offload/offloadserver/api/quest/service/QuestRewardService.java
src/main/java/site/offload/offloadserver/db/charactermotion/entity/GainedCharacterMotion.java
src/main/java/site/offload/offloadserver/db/quest/embeddable/RewardList.java
src/main/java/site/offload/offloadserver/db/quest/entity/CompleteQuest.java
src/main/java/site/offload/offloadserver/db/quest/entity/QuestReward.java
src/main/java/site/offload/offloadserver/db/quest/repository/CompleteQuestRepository.java
src/main/java/site/offload/offloadserver/db/quest/repository/ProceedingQuestRepository.java
src/main/java/site/offload/offloadserver/db/quest/repository/QuestRewardRepository.java

* 완료된 퀘스트를 저장하는 엔티티를 생성했습니다.
* 보상 모션을 찾아와 얻은 보상을 저장했습니다.
* 완료된 퀘스트에 퀘스트 추가, 진행중인 퀘스트에서 삭제를 구현했습니다.
* 완료된 퀘스트인지 판단하고 그렇지 않아야 proceeding quest로 추가하는 작업이 필요합니다.

[hotfix] : 모션보상 관련 퀘스트 일부 저장

---

src/main/java/site/offload/offloadserver/api/member/controller/MemberController.java
src/main/java/site/offload/offloadserver/api/member/controller/MemberControllerSwagger.java
src/main/java/site/offload/offloadserver/api/member/dto/request/AuthPositionRequest.java
src/main/java/site/offload/offloadserver/api/member/dto/response/AuthAdventureResponse.java
src/main/java/site/offload/offloadserver/api/member/dto/response/VerifyPositionDistanceResponse.java
src/main/java/site/offload/offloadserver/api/member/dto/response/VerifyQrcodeResponse.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/db/character/entity/Character.java

- 사용자 위치 정보 대조 API 생성 
- 장소 카테고리에 따라 위치 정보만으로 인증을 하는 API, 위치 정보와 Qr코드로 인증을 하는 API를 나눠서 작성했습니다.
- 관련 DTO 따로 나누고, MemberUseCase에서 로직을 추가했습니다.

[feat] 위치 정보 대조 API 생성

---

src/main/java/site/offload/offloadserver/api/member/dto/request/MemberProfileUpdateRequest.java
src/main/java/site/offload/offloadserver/db/member/embeddable/Birthday.java

- [MemberProfileUpdateRequest.java](https://github.com/Team-Offroad/Offroad-server/compare/task/null%ED%83%80%EC%9E%85%EC%B2%B4%ED%81%AC?expand=1#diff-db6ccbff74f70508aa38614a505eca25da4ee93595e6167be3d0f8f3f0920ecb)에서 생년월일의 타입을 Integer로 수정해서 null을 허용하게 했습니다.
- 사용자 생년월일 입력은 선택이므로, 요청으로 null이 전달 될 시 이에 대한 처리가 필요했습니다.

[chore] 프로필 업데이트 생년월일 타입 수정

---

src/main/java/site/offload/offloadserver/api/member/dto/response/MemberAdventureInformationResponse.java
src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/common/jwt/JwtTokenProvider.java

- 클라이언트  측 요청사항에 따라 access token의 유효 기간을 늘렸습니다. 
- 탐험 정보 조회 API에서 반환할 캐릭터 url을 기본 이미지 url과 로티 url 둘 다 포함시켰습니다.
- 그에 따라 서비스 로직을 수정하고 DTO 반환 값을 다시 설정했습니다.
- 기본 이미지의 경우 항상 반환되지만 ,로티에 대한 url은 유저가 획득한 로티일 경우에만 반환하도록 했습니다.

[fix] 탐험정보 조회 모션이미지 기본이미지 둘다 반환

---

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java
src/main/java/site/offload/offloadserver/db/character/entity/Character.java

- Character 필드에 탐험 인증 실패 시 반환할 이미지 경로 필드를 추가했습니다(QR코드 실패 시, 위치 정보 대조 실패 시)
- 실패 시 이미지가 서로 다르므로, 필드를 추가하고 각 경우에 따라 다른 필드의 이미지 url을 반환하도록 했습니다.

[chore] 탐험 실패 시 이미지 반환

---

src/main/java/site/offload/offloadserver/api/member/usecase/MemberUseCase.java

- MemberUseCase의 processQuests() 에서 for 문 안에 return;을 continue로 수정했습니다. 
- 퀘스트 5번 (탐험 50번 성공)에 해당하는 진행중인 퀘스트 테이블의 클리어 카운트가, 탐험 인증 성공 시 정상적으로 증가함을 로컬에서 확인했습니다.

[fix] 탐험 인증 시 퀘스트 클리어 카운트 증가 문제

---

offroad-api/src/main/java/site/offload/api/OffloadserverApiApplication.java

- ComponentScan 시에 db module을 포함하지 않아,  @JpaAuditingConfiguration을 Spring Bean으로 등록하지 못하는 문제를 해결했습니다.

fix: Component Scan db module 추가

---

offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java

- 모험 정보 조회 API의 getMemberAdventureInformation의 코드를 수정했습니다
- 닉네임 입력, 캐릭터 선택 둘 다 안한 경우 / 닉네임 입력 했는데 캐릭터 선택 안 한 경우로 나눠서 반환 값을 수정했습니다
- 로컬에서 로그인 직후, 닉네임 입력 후, 캐릭터 입력 후 각각 모험 정보 조회 API를 요청해서 반환 되는 값을 확인했습니다

fix: 닉네임, 캐릭터 선택 여부에 따른 모험 정보 조회 api 반환값 수정

---

offroad-api/src/main/java/site/offload/api/character/service/GainedCharacterService.java
offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java
offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
offroad-api/src/main/resources/application-local.yaml
offroad-api/src/test/java/site/offload/api/character/CharacterEntityFixtureCreator.java
offroad-api/src/test/java/site/offload/api/character/CreateCharacter.java
offroad-api/src/test/java/site/offload/api/character/service/GainedCharacterServiceTest.java
offroad-api/src/test/java/site/offload/api/character/usecase/GainedCharacterUseCaseTest.java
offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java
offroad-db/src/main/java/site/offload/db/character/repository/GainedCharacterRepository.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

https://github.com/Team-Offroad/Offroad-server/blob/bbc2bf8cd731c73f5905de668078b06387d0cfa8/offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java#L306-L319
* 모든 캐릭터를 가져온 후, 하나씩 조회해가며 보유한 캐릭터와 그렇지 않은 캐릭터를 구분했습니다.
* 보유 캐릭터인 경우 기본 이미지 URL, 미보유 캐릭터인 경우 썸네일 이미지 URL을 담아 보내도록 했습니다.
https://github.com/Team-Offroad/Offroad-server/blob/bbc2bf8cd731c73f5905de668078b06387d0cfa8/offroad-api/src/main/resources/application-local.yaml#L8
https://github.com/Team-Offroad/Offroad-server/blob/bbc2bf8cd731c73f5905de668078b06387d0cfa8/offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java#L51
https://github.com/Team-Offroad/Offroad-server/blob/bbc2bf8cd731c73f5905de668078b06387d0cfa8/offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java …

[feat] : 유저가 보유한 캐릭터 목록 조회 API 구현 및 GOOGLE 소셜로그인 시 플랫폼 저장

---

offroad-api/src/main/java/site/offload/api/OffloadserverApiApplication.java
offroad-api/src/main/java/site/offload/api/auth/jwt/JwtTokenProvider.java
offroad-api/src/main/java/site/offload/api/emblem/controller/EmblemController.java
offroad-api/src/main/java/site/offload/api/emblem/dto/response/EmblemResponse.java
offroad-api/src/main/java/site/offload/api/emblem/dto/response/EmblemsResponse.java
offroad-api/src/main/java/site/offload/api/emblem/usecase/EmblemUseCase.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
offroad-api/src/main/java/site/offload/api/quest/service/QuestRewardService.java
offroad-api/src/test/java/site/offload/api/questReward/repository/QuestRewardRepositoryTest.java
offroad-api/src/test/java/site/offload/api/questReward/service/QuestRewardServiceTest.java
offroad-api/src/test/java/site/offload/api/questReward/usecase/QuestRewardUseCaseTest.java
offroad-db/src/main/java/site/offload/db/quest/entity/QuestRewardEntity.java
offroad-db/src/main/java/site/offload/db/quest/repository/QuestRewardRepository.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

https://github.com/Team-Offroad/Offroad-server/blob/42e931c83908823f2af2d4a9e72c8c336c5f6cda/offroad-api/src/main/java/site/offload/api/emblem/usecase/EmblemUseCase.java#L62-L80
* 우선 퀘스트 보상으로 칭호를 가지는 퀘스트 리워드 엔티티들을 불러옵니다.
* 이후 내가 보유한 엠블렘 엔티티들을 불러오고 엠블렘 코드들을 모았습니다.
* 퀘스트 보상으로 칭호를 가지는 퀘스트 리워드 엔티티들을 비교하며 엠블렘 코드가 내가 가지고 있는 코드라면 보유, 아니면 미보유로 분류합니다. 퀘스트 이름은 questService의 메소드를 사용해서 불러왔습니다. 
* User가 보유하거나 보유하지 않은 칭호 목록을 조회하기 때문에 /users/emblems로 url을 설정하려고 했으나 이미 존재할 뿐더러, 결국 emblem이라는 자원을 조회하는 것이라 생각해서 URL을 /emblems로 설정했습니다. 
https://github.com/Team-Offroad/Offroad-server/blob/42e931c83908823f2af2d4a9e72c8c336c5f6cda/offroad-api/src/test/java/site/offload/api/questReward/repository/QuestRewardRepositoryTest.java#L54-L58
* 이 API의 핵심 중 하나는 Repository에서 쿼리문을 이용하여 보상이 칭호인 엔티티들을 제대로 불러오는지의 여부라고 생각해서 이를 …

[feat] : 칭호 목록 조회 API

---

offroad-api/src/main/java/site/offload/api/character/controller/CharacterController.java
offroad-api/src/main/java/site/offload/api/character/controller/CharacterControllerSwagger.java
offroad-api/src/main/java/site/offload/api/character/dto/response/CharacterDetailResponse.java
offroad-api/src/main/java/site/offload/api/character/usecase/CharacterUseCase.java
offroad-api/src/main/java/site/offload/api/charactermotion/controller/CharacterMotionController.java
offroad-api/src/main/java/site/offload/api/charactermotion/controller/CharacterMotionControllerSwagger.java
offroad-api/src/main/java/site/offload/api/coupon/controller/CouponControllerSwagger.java
offroad-api/src/main/java/site/offload/api/emblem/controller/EmblemControllerSwagger.java
offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java
offroad-api/src/test/java/site/offload/api/character/service/CharacterServiceTest.java
offroad-api/src/test/java/site/offload/api/character/service/GainedCharacterServiceTest.java
offroad-api/src/test/java/site/offload/api/character/usecase/GainedCharacterUseCaseTest.java
offroad-api/src/test/java/site/offload/api/charactermotion/service/CharacterMotionServiceTest.java
offroad-api/src/test/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCaseTest.java
offroad-api/src/test/java/site/offload/api/fixture/CharacterEntityFixtureCreator.java
offroad-api/src/test/java/site/offload/api/member/usecase/AuthAdventureUseCaseTest.java
offroad-db/src/main/java/site/offload/db/character/entity/CharacterEntity.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

* 캐릭터를 선택하면 보여지는 정보를 응답하는 API를 작성했습니다.
* 누락된 swagger를 작성했습니다.

[feat] : 캐릭터 선택시 상세 정보 조회 API 구현 및 swagger 작성

---

offroad-api/src/main/java/site/offload/api/quest/controller/QuestController.java
offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
offroad-api/src/main/java/site/offload/api/quest/dto/request/QuestDetailListRequest.java
offroad-api/src/main/java/site/offload/api/quest/dto/response/QuestDetailListResponse.java
offroad-api/src/main/java/site/offload/api/quest/dto/response/QuestDetailResponse.java
offroad-api/src/main/java/site/offload/api/quest/service/CompleteQuestService.java
offroad-api/src/main/java/site/offload/api/quest/service/ProceedingQuestService.java
offroad-api/src/main/java/site/offload/api/quest/service/QuestService.java
offroad-api/src/main/java/site/offload/api/quest/usecase/QuestUseCase.java
offroad-api/src/test/java/site/offload/api/fixture/CompleteQuestEntityFixture.java
offroad-api/src/test/java/site/offload/api/fixture/ProceedingQuestEntityFixture.java
offroad-api/src/test/java/site/offload/api/quest/service/CompleteQuestServiceTest.java
offroad-api/src/test/java/site/offload/api/quest/service/ProceedingQuestServiceTest.java
offroad-api/src/test/java/site/offload/api/quest/service/QuestServiceTest.java
offroad-api/src/test/java/site/offload/api/quest/usecase/QuestUseCaseTest.java
offroad-db/src/main/java/site/offload/db/quest/entity/QuestEntity.java
offroad-db/src/main/java/site/offload/db/quest/repository/CompleteQuestRepository.java
offroad-db/src/main/java/site/offload/db/quest/repository/ProceedingQuestRepository.java
offroad-db/src/main/java/site/offload/db/quest/repository/QuestRepository.java
offroad-enum/src/main/java/site/offload/enums/place/PlaceCategory.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

- QuestEntity에 보상, 달성 조건, 설명을 나타낼 수 있는 text 관련 필드를 추가했습니다
- 화면에 보여지는 보상, 달성 조건 텍스트의 경우 필드를 추가하지 않고 앱에서 처리할 지 아니면 필드를 추가할지 고민하다,
퀘스트 개수가 그렇게 많지 않은 것과 문자열을 다루는 구현의 복잡성 때문에 필드에 추가하는 방식을 선택했습니다
- 화면 설계서 요구사항에 따라 퀘스트들을 정렬해서 응답합니다
- 퀘스트 달성 조건, 쿠폰의 정확한 텍스트 형식은 아직 정하지 않은거 같아 예시로 남겼습니다

feat: 퀘스트 목록 조회 api 구현

---

offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java
offroad-api/src/main/java/site/offload/api/member/dto/request/MarketingAgreeRequest.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
offroad-api/src/test/java/site/offload/api/member/usecase/MemberUseCaseTest.java
offroad-db/src/main/java/site/offload/db/member/entity/MemberEntity.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

* 마케팅 수신 여부 확인 API를 작성했습니다.
* 개인정보 수집 동의, 위치 기반 동의 등 4가지 약관 중 3가지는 필수고 마케팅만 선택이었기 때문에 마케팅 여부만 확인하도록 했습니다.
* MemberEntity내부에 마케팅 수신 여부를 나타내는 boolean값과 이를 update하는 메소드를 추가했습니다.

[feat]: 마케팅 수신 여부 동의 API 

---

offroad-api/src/main/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCase.java
offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponListUseCase.java
offroad-api/src/main/java/site/offload/api/emblem/usecase/EmblemUseCase.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
offroad-api/src/test/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCaseTest.java
offroad-api/src/test/java/site/offload/api/coupon/usecase/CouponListUseCaseTest.java
offroad-db/src/main/java/site/offload/db/character/entity/GainedCharacterEntity.java
offroad-db/src/main/java/site/offload/db/charactermotion/entity/GainedCharacterMotionEntity.java
offroad-db/src/main/java/site/offload/db/coupon/entity/GainedCouponEntity.java
offroad-db/src/main/java/site/offload/db/emblem/entity/GainedEmblemEntity.java

* 신규 획득 여부를 응답한 후에 더 이상 신규 획득이 아님을 나타낼 수 있도록 갱신하게 했습니다.
* 캐릭터, 캐릭터모션, 쿠폰, 칭호 usecase에서 Gained~Entity에 원래 상태를 먼저 저장한 후 이를 반환하도록 설정했습니다.
* 저장 후 더 이상 신규 획득이 아니기 때문에 상태를 업데이트 해주는 메소드를 이용해 업데이트 했습니다.
* 클릭 시 New상태가 아니라는 조건이 있긴 했지만, 클릭시에도 페이지를 벗어나는 것은 똑같다고 판단하여서 이러한 메소드들을 추가했습니다.

[feat] : 신규 획득 여부 갱신 구현

---

offroad-api/build.gradle
offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
offroad-api/src/main/java/site/offload/api/place/controller/PlaceController.java
offroad-api/src/main/java/site/offload/api/place/controller/PlaceControllerSwagger.java
offroad-api/src/main/java/site/offload/api/place/dto/request/RegisteredPlacesRequest.java
offroad-api/src/main/java/site/offload/api/place/dto/request/UnvisitedPlacesRequest.java
offroad-api/src/main/java/site/offload/api/place/dto/response/UnvisitedPlaceResponse.java
offroad-api/src/main/java/site/offload/api/place/dto/response/UnvisitedPlacesResponse.java
offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java
offroad-api/src/main/java/site/offload/api/place/service/VisitedPlaceService.java
offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
offroad-api/src/main/resources/application-local.yaml
offroad-api/src/test/java/site/offload/api/questReward/repository/QuestRewardRepositoryTest.java
offroad-db/build.gradle
offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java
offroad-db/src/main/java/site/offload/db/place/repository/VisitedPlaceRepository.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

-  요구 사항에 맞춰서 API를 수정했습니다. 기존 장소 조회 API는 스펙을 유지하고, 안가본곳을 조회하는 API를 별도로 구현했습니다.
- 장소는 기본적으로 가까운 순으로 조회하고, Query String으로 isBounded를 받아, True인 경우 기존 API 동작 방식인 주변으ㅢ 장소를 조회하는 형태로 구현.
- db module에서 test를 짤려고 헀는데 Spring Bean 등록이 안되네요 ..! 나중에 해결해보겠습니다.

refactor: 장소 조회 API 수정

---

offroad-api/src/main/java/site/offload/api/member/usecase/SocialLoginUseCase.java
offroad-api/src/main/resources/application-dev.yaml
offroad-api/src/main/resources/application-local.yaml
offroad-enum/src/main/java/site/offload/enums/member/SocialPlatform.java
offroad-external/src/main/java/site/offload/external/oauth/dto/SocialLoginRequest.java
offroad-external/src/main/java/site/offload/external/oauth/kakao/KakaoSocialLoginService.java
offroad-external/src/main/java/site/offload/external/oauth/kakao/request/KakaoAccessTokenClient.java
offroad-external/src/main/java/site/offload/external/oauth/kakao/request/KakaoInfoClient.java
offroad-external/src/main/java/site/offload/external/oauth/kakao/response/KakaoAccessTokenResponse.java
offroad-external/src/main/java/site/offload/external/oauth/kakao/response/KakaoInfoResponse.java

* 카카오 소셜 로그인 API를 FeignClient를 사용하여 구현했습니다.
* JSON parse error: Cannot deserialize value of type라는 에러가 발생하여 소셜 플랫폼의 분기처리에서 수정을 하였습니다.
* yaml파일이 수정됨에 따라서 github actions 또한 수정이 필요합니다. 
* 현재 이용중인 client-id는 테스트 앱의 어플리케이션입니다. 그렇기에 나중에 본 앱을 이용하기 위해서는 yaml파일에서 redirect-uri와 client-id의 수정이 필요합니다.
* 테스트 앱이 아닌 본 앱에서 개인정보 동의항목에 이름을 추가시키려면 사업자 번호가 있어야 하는데 이에 대해서 어떻게 처리해야 할지 논의하면 좋을 것 같습니다.

[feat]: 카카오 소셜 로그인 API 구현

---

offroad-api/src/main/java/site/offload/api/member/controller/MemberController.java
offroad-api/src/main/java/site/offload/api/member/controller/MemberControllerSwagger.java
offroad-api/src/main/java/site/offload/api/member/dto/request/TermsAgreeRequest.java
offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharacterResponse.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java
offroad-api/src/main/resources/application-local.yaml
offroad-api/src/test/java/site/offload/api/member/usecase/MemberUseCaseTest.java
offroad-db/src/main/java/site/offload/db/member/entity/MemberEntity.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

* 획득 캐릭터 응답 값 중 CharacterId의 앞 부분을 소문자로 수정했습니다
* 약관 동의 여부를 저장할 수 있도록 MemberEntity에 필드를 추가했습니다.

[refactor] : 캐릭터 아이디 철자 수정 및 약관 동의 여부 저장

---

offroad-api/build.gradle
offroad-api/src/main/java/site/offload/api/member/usecase/AuthAdventureUseCase.java
offroad-api/src/main/java/site/offload/api/place/controller/PlaceController.java
offroad-api/src/main/java/site/offload/api/place/controller/PlaceControllerSwagger.java
offroad-api/src/main/java/site/offload/api/place/dto/request/RegisteredPlacesRequest.java
offroad-api/src/main/java/site/offload/api/place/dto/request/UnvisitedPlacesRequest.java
offroad-api/src/main/java/site/offload/api/place/dto/response/UnvisitedPlaceResponse.java
offroad-api/src/main/java/site/offload/api/place/dto/response/UnvisitedPlacesResponse.java
offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java
offroad-api/src/main/java/site/offload/api/place/service/VisitedPlaceService.java
offroad-api/src/main/java/site/offload/api/place/usecase/PlaceUseCase.java
offroad-api/src/main/resources/application-local.yaml
offroad-api/src/test/java/site/offload/api/questReward/repository/QuestRewardRepositoryTest.java
offroad-db/build.gradle
offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java
offroad-db/src/main/java/site/offload/db/place/repository/VisitedPlaceRepository.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

- 장소 조회에서 작성했던 쿼리에 문제가 있어, PlaceRepository의 조회 Query를 수정했습니다.
- nativeQuery에서 LIMIT query를 사용할 수 없기 때문에 parameter를 `Pageable` 로 수정했습니다.
-test code 작성시에 @JpaAuditing과 관련된 issue가 있네요 .. 원인 파악을 해봐야 할 것 같습니다.
- DataGrip의 SQL query test 했습니다.

fix: 장소 조회시에 Query 수정

---

offroad-api/src/main/java/site/offload/api/member/dto/response/GainedCharactersResponse.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java

* 대표 캐릭터에 왕관 표시를 해야하는 이슈가 있었는데, 대표 캐릭터의 아이디를 따로 넘기는 부분이 존재하지 않다는 클라이언트 분들의 말씀이 있어서 이에 대해서 수정하였습니다.

[fix] : 캐릭터 조회 API에 대표 캐릭터 ID 추가

---

offroad-api/src/main/java/site/offload/api/announcement/controller/AnnouncementController.java
offroad-api/src/main/java/site/offload/api/announcement/controller/AnnouncementControllerSwagger.java
offroad-api/src/main/java/site/offload/api/announcement/dto/response/AnnouncementDetailResponse.java
offroad-api/src/main/java/site/offload/api/announcement/dto/response/AnnouncementsResponse.java
offroad-api/src/main/java/site/offload/api/announcement/service/AnnouncementService.java
offroad-api/src/main/java/site/offload/api/announcement/usecase/AnnouncementUseCase.java
offroad-db/src/main/java/site/offload/db/announcement/entity/AnnouncementEntity.java
offroad-db/src/main/java/site/offload/db/announcement/repository/AnnouncementRepository.java
offroad-enum/src/main/java/site/offload/enums/response/SuccessMessage.java

* 공지사항 목록을 불러오는 API를 구현했습다.
* 중요 공지임을 표시하기 위해 AnnounceEntity에 isImortant 필드를 추가했습니다.
* 클라이언트분들과 논의가 필요합니다. (ex : 링크가 포함된 공지사항인 경우의 처리)

 [feat] : 공지사항 목록 조회 API 구현

---

offroad-api/src/main/java/site/offload/api/charactermotion/usecase/CharacterMotionUseCase.java
offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponListUseCase.java
offroad-api/src/main/java/site/offload/api/emblem/usecase/EmblemUseCase.java
offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java

- 신규 획득 여부를 나타내야 하는 각 도메인의 유스케이스에서 조회 메소드의 트랜잭션 상태가 읽기 전용으로 되어있어서(reaOnly=true 옵션) DB 상태를 업데이트 하는 코드(updateNewGainedStatus())가 작동하지 않아, 이 부분을 제거했습니다.
- 신규 획득 여부 표시가 필요한 캐릭터, 캐릭터 모션, 쿠폰 목록, 칭호 목록의 조회 메소드를 수정했습니다.
- 이에 관한 테스트 코드가 통과한 이유는, 영속성 계층까지는 테스트 범위에 들어가지 않아 통과했던 것 같습니다.

fix: 신규 획득 여부가 바뀌지 않는 오류 수정

---

offroad-api/src/main/java/site/offload/api/announcement/dto/response/AnnouncementDetailResponse.java
offroad-api/src/main/java/site/offload/api/announcement/usecase/AnnouncementUseCase.java
offroad-common/src/main/java/site/offload/common/util/StringListConvert.java
offroad-db/src/main/java/site/offload/db/announcement/entity/AnnouncementEntity.java
offroad-db/src/main/java/site/offload/db/util/StringListConvert.java

* 공지사항 조회 API의 반환 값으로 링크 보유 여부, 링크 리스트를 추가 했습니다.
* 이에 따라 공지사항 필드에 해당 값들을 추가했고, 링크 리스트를 DB에 저장하기 위해 문자열 리스트를 DB에 저장할 수 있게 도와주는 util 클래스를 하나 설정했습니다.

[refactor]: 공지사항 응답 값 수정

---

offroad-api/src/main/java/site/offload/api/coupon/usecase/CouponApplyUseCase.java
offroad-api/src/main/java/site/offload/api/place/service/PlaceService.java
offroad-api/src/test/java/site/offload/api/place/service/PlaceEntityServiceTest.java
offroad-db/src/main/java/site/offload/db/place/repository/PlaceRepository.java

- close #225 
- 쿠폰 사용 api에서, 잘못된 쿠폰 사용코드(해당하는 장소가 없을경우)를 요청 시 응답값으로 false가 되도록 수정했습니다.
- PlaceService에서 쿠폰 코드로 장소값을 찾는 메소드에 대한 테스트 케이스 추가했습니다.

fix: 장소에 없는 쿠폰사용코드 체크 수정

---

offroad-api/src/main/java/site/offload/api/member/usecase/MemberUseCase.java

- 기존 반환되던 url이 presign 작업이 되어있지 않아 추가했습니다.
- 회의 내용대로, 디자인분들한테 상반신 이미지 받기전까지 기본이미지로 대체해놓았습니다.

fix: 반환 캐릭터 이미지 presign url 추가

---

offroad-api/src/main/java/site/offload/api/quest/controller/QuestController.java
offroad-api/src/main/java/site/offload/api/quest/controller/QuestControllerSwagger.java
offroad-api/src/main/java/site/offload/api/quest/dto/request/QuestDetailListRequest.java
offroad-api/src/main/java/site/offload/api/quest/dto/response/QuestDetailResponse.java
offroad-api/src/main/java/site/offload/api/quest/usecase/QuestUseCase.java
offroad-api/src/test/java/site/offload/api/quest/usecase/QuestUseCaseTest.java
offroad-db/src/main/java/site/offload/db/quest/entity/ProceedingQuestEntity.java

- 퀘스트 목록(전체 목록 and 진행 중) 반환 시 무한스크롤을 고려해 페이지네이션 작업을 진행했습니다.
- 기존에는 Data Jpa의 Pageable 인터페이스를 구현해서 db에 직접 쿼리해 구현할 생각이었는데, 서비스 로직에 정렬 조건과 필터 등 다양한 변수때문에 쿼리가 너무 복잡해져서 유스케이스에서 직접 코드로 구현했습니다. 
- 직접 코드로 구현하기 때문에 이 경우 전체 목록을 무조건 가져와야돼서 성능 상 단점이 있을 수 있으나, 퀘스트 도메인 특성 상 데이터의 수가 방대하지는 않기 때문에 이 부분은 괜찮을 것 같습니다( 혹시 우려되신다면 코멘트 남겨주세용)
- 기존에 제가 작성했던 코드가 다시보니 잘 읽히지 않고 지저분한 것 같아 메소드 레벨에서 조금 리팩토링했습니다.
- 기존 테스트 코드를  페이지네이션을 추가하여 수정했습니다.

feat: 퀘스트 목록 페이지네이션 구현, 리팩토링
